- hosts: all
  gather_facts: false
  become: yes

  roles:
    - create-docker
    - remove-containers-ansible
    - create-network
    - launch-database
    - launch-app
    - launch-proxy
    - launch-front