name: CI devops 2022 CPE 
on:
  #to begin you want to launch this job in main (master for me i don't rename it) and develop
  push:
    branches:
      - master
      - develop
  pull_request:
jobs: 
  test-backend:
    runs-on: ubuntu-18.04 
    steps:
    #checkout your github code using actions/checkout@v2.3.3
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 11
      uses: actions/setup-java@v2 #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      with:
        distribution: 'temurin'
        java-version: '11'
      #finally build your app with the latest command
    - name: Build and test with Maven 
      run: mvn -B package --file pom.xml